import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LogoColor from '../img/LogoColor.png'
import GetDate from '../components/GetDate'
import GetDays from '../components/GetDays'
import RowsandCols from '../components/Cards/infoColRow'


export default function Home() {
  return (
    <div className='w-full'>
      <Head>
        <title>HORARIOS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>

      <div className='w-full bg-white flex justify-center mb-4 pt-2'>
        <div className='md:w-1/12 h-fit pb-2'>
          <Image src={LogoColor} alt="Logo" />
        </div>
      </div>

      <GetDays />
      <GetDate />
      
      <div>
        <RowsandCols />
      </div>

    </div>
  )
}
